In [1]:
import h5py
import os.path

def save_file(folder,name,data,xaxis,yaxis):
    path = folder + '/' + name
    if not os.path.exists(path):
        with h5py.File(path, 'w') as f:
            f.create_dataset('data', data = data)
            f.create_dataset('X_'+xaxis, data = 0)
            f.create_dataset('Y_'+yaxis, data = 0)
            f.close()
            print('The file has been saved')
    else:
        print('The file already exists')
    return None

def rewrite_file(folder,name,data,xaxis,yaxis):
    path = folder + '/' + name
    if os.path.exists(path):
        with h5py.File(path, 'w') as f:
            f.create_dataset('data', data = data)
            f.create_dataset('X_'+xaxis, data = 0)
            f.create_dataset('Y_'+yaxis, data = 0)
            f.close()
            print('The file has been rewrited')
    else:
        print('The file does not exist')
    return None

def read_file(folder,name):
    path = folder + '/' + name
    with h5py.File(path, 'r') as f:
        data = f['data'][:]
        print(f.keys())
        f.close()
    print('Data shape =',data.shape)
    return data

In [2]:
import numpy as np
import torch

In [3]:
A = torch.tensor(np.arange(10).reshape(2,5))

In [4]:
import datetime

datetime.datetime.now()

datetime.datetime(2022, 1, 22, 11, 55, 54, 164596)

In [5]:
text = 'sadsda cdscdcsd 5545 fsdfsf'
path = 'Q'
with h5py.File(path, 'w') as f:
    f.create_dataset('data', data = A)
    f.create_dataset('data1', data = A)
    f.create_dataset('description', data = text)

In [6]:
with h5py.File(path, 'r') as f:
    print(f.keys())
    data = f['description'][:]
data

<KeysViewHDF5 ['data', 'data1', 'description']>


ValueError: Illegal slicing argument for scalar dataspace

In [ ]:
data

In [ ]:
import torch
import torch.nn as nn

class function(torch.nn.Module):
    def __init__(self,th=None):
        super(function, self).__init__()
        self.th = th
        
    def forward(self, x):
        return x * self.th

    def extra_repr(self):
        return 'opt_th={}'.format(self.th)
    
system = nn.Sequential()
inp  = 2
n = 3
for i in range(0,n):
    # find optimal threshold
    th = system.forward(inp)
    # add this layer into model
    system.add_module('layer_'+str(i),function(th))
    
system.named_modules, system.forward(3)

In [ ]:
class Computer():
    def __init__(self, computer, ram, ssd):
        self.computer = computer
        self.ram = ram
        self.ssd = ssd

# Если создать дочерний класс `Laptop`, то будет доступ 
# к свойству базового класса благодаря функции super().
class Laptop(Computer):
    def __init__(self, computer, ram, ssd, model):
        super(Laptop).__init__()
        self.model = model


In [ ]:
lap1 = Computer('lenovo',512,256)

In [ ]:
lap1.computer

In [ ]:
lap2 = Laptop('lenovo',512,256,'ssw')

In [ ]:
lap2.model

In [ ]:
lap2.m

In [ ]:
mod_list = ['QPSK','QAM16','QAM64', 'QAM256']
mod_alloc = ['QAM64', 'QPSK', 'QAM16', 'QAM256', 'QPSK','QPSK', 'QAM16', 'QAM256']

idxs = []
for item in mod_alloc:
    idx = np.argmax(np.array(mod_list) == item)
    idxs.append(idx)
    
    
one_hot = np.zeros([len(mod_list),len(mod_alloc)])
for i,idx in enumerate(idxs):
    one_hot[idx,i] = 1
    
one_hot

In [ ]:
one_hot_wei = np.zeros([4,4])
counter = np.zeros(4)
for item in mod_alloc:
    idx = np.argmax(np.array(mod_list) == item)
    counter[idx] += 1
counter

In [ ]:
np.eye(4) @  counter

In [ ]:
%pylab inline

def PAPR(x):
    return -(x - 2)**2 + 5

bnd = np.array([0,6])

ths = np.linspace(bnd[0],bnd[1],100)
plt.plot(ths,PAPR(x))
plt.grid()

In [ ]:
bnd = np.array([0,6])

for i in range(25):
    # find midddle point
    mid_point = (bnd[0] + bnd[-1])/2
    # and result in this point
    mid_res = PAPR(mid_point)
    # find edge results
    e1 = PAPR(bnd[0])
    e2 = PAPR(bnd[1])
    edg_res = [e1,e2]
    # find lowest element
    idx_del = np.array([edg_res[0],edg_res[1],mid_res]).argmin()
    # delete corresponding bound
    bnd = np.delete(np.array([bnd[0],bnd[-1],mid_point]),idx_del)
bnd

In [ ]:
1/2**25

In [ ]:
PAPR(bnd[0])

array([ 0.        ,  0.89155923, -0.80758169, -0.16004509,  0.95255185,
       -0.70278422, -0.31596412,  0.98898712, -0.57986856, -0.4637374 ,
        0.99992572, -0.44200354, -0.59955527,  0.98508564, -0.29274341,
       -0.71991625,  0.94484948, -0.13593619, -0.82171736,  0.88025454,
        0.02437555, -0.90233411,  0.79296611,  0.18405888, -0.95968816,
        0.68523456,  0.33899705, -0.99230088,  0.55983726,  0.48519569,
       -0.9993315 ,  0.42000702,  0.61888569, -0.98059877,  0.26934875,
        0.73662046, -0.93658562,  0.11174651,  0.83536471, -0.86842674,
       -0.04873662,  0.91257277, -0.77787931, -0.20796329,  0.96625417,
       -0.6672777 , -0.36182854,  0.99502497, -0.53947327, -0.50636564])

In [24]:
%pylab inline
plt.figure(5,5)
plt.plot(np.sin(np.linspace(0,100)),color='r',linewidth=2)

Populating the interactive namespace from numpy and matplotlib


TypeError: from_bounds() argument after * must be an iterable, not int

In [1]:
import pandas as pd
d = pd.read_csv('N=3.csv',sep=' ')
d = d.drop('ANL_Allocation', 1)
d = d.drop('Unnamed: 0', 1)
d = d.drop('MOD_Allocation_n', 1)
d.sample(3)

N_UE         PTX_Allocation     RB_Allocation  \
861     5  [16. 26. 30.  6. 22.]  [ 9 18  5  5 13]   
953     5  [15. 18. 17. 14. 36.]  [14  6 12  6 12]   
972     5  [ 3. 28. 33. 16. 20.]  [ 5 12 14  7 12]   

                                        MOD_Allocation  OPT_th_mean  \
861  ['QAM16', 'QAM1024', 'QAM256', 'QAM1024', 'QAM...     6.997070   
953        ['QAM64', 'QPSK', 'QAM64', 'QAM16', 'QPSK']     6.545898   
972  ['QAM1024', 'QAM256', 'QAM256', 'QAM256', 'QAM...     6.997070   

     OPT_th_max  
861         NaN  
953         NaN  
972         NaN

In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


$$ C \approx N_{RB} \cdot \sqrt{ANL} $$

In [690]:
%pylab inline
from itertools import *

def two_gr(idxs,m):
    NUE = np.arange(len(idxs))
    k = len(NUE)//2

    groups = []
    out = []
    
    if len(NUE) == 2:
        groups.append([np.array([0]),np.array([1])])
    if len(NUE) >= 3:
        if 1:
            comb_list = list(combinations(NUE,m))
            idx_G1 = [np.array(item) for item in comb_list]
            idx_G2 = [np.delete(NUE,[item[0:k+1]]) for item in idx_G1]

            length = len(idx_G1)
            if len(NUE) % 2 == 0 and m==k:
                length = len(idx_G1)//2

            for i in range(length):
                groups.append([idx_G1[i],idx_G2[i]])

    group_options = len(groups)
    for m in range(group_options):
        group_division = groups[m]
        out.append([idxs[group_division[0]],idxs[group_division[1]]])
    return out

buff = []
def f(a, n, p):
    if n:
        for i in range(n+1, 0, -1):
            if i <= p:
                f(a+[i], n-i, i)
    else:
        buff.append([*a])
    return buff

def get_all_splits(n,groups):
    all_splits = []
    buff = f([], n, n)
    for item in buff:
        if len(item) == groups:
            all_splits.append(np.array(item))
    return all_splits

NUE = np.arange(10)

all_splits = get_all_splits(n=len(NUE),groups=3)


ress = []

k = len(NUE)//2

# 1 group
ress.append([NUE,np.array([]),np.array([])])
if len(NUE) == 2:
    ress.append([np.array([0]),np.array([1]),np.array([])])

# 2 groups
if len(NUE) >= 3:
    for m in range(1,k+1):
        comb_list = list(combinations(NUE,m))
        idx_G1 = [np.array(item) for item in comb_list]
        idx_G2 = [np.delete(NUE,[item[0:k+1]]) for item in idx_G1]
        length = len(idx_G1)
        if len(NUE) % 2 == 0 and m==k:
            length = len(idx_G1)//2
        for i in range(length):
            ress.append([idx_G2[i],idx_G1[i],np.array([])])

# 3 groups
if len(NUE) == 3:
    ress.append([np.array([0]),np.array([1]),np.array([2])])
elif len(NUE) >=3:
    for split in all_splits:
    #     split = all_splits[3]
        m,n,k = split[0],split[1],split[2]
        comb_list0 = list(combinations(NUE,m))
        idx_G1 = [np.array(item) for item in comb_list0]
        idx_G23 = [np.array(np.delete(NUE,item)) for item in idx_G1]
        q = [two_gr(item,n) for item in idx_G23]
        for item1,item2 in zip(idx_G1,q):
            for item3 in item2:
                ress.append([item1]+item3)
print(len(ress))
ress

Populating the interactive namespace from numpy and matplotlib
11417


/home/stas/anaconda3/lib/python3.8/site-packages/IPython/core/magics/pylab.py:159: UserWarning: pylab import has clobbered these variables: ['compress', 'product', 'repeat', 'f', 'split']
`%matplotlib` prevents importing * from pylab and numpy
  warn("pylab import has clobbered these variables: %s"  % clobbered +


[[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
  array([], dtype=float64),
  array([], dtype=float64)],
 [array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([0]), array([], dtype=float64)],
 [array([0, 2, 3, 4, 5, 6, 7, 8, 9]), array([1]), array([], dtype=float64)],
 [array([0, 1, 3, 4, 5, 6, 7, 8, 9]), array([2]), array([], dtype=float64)],
 [array([0, 1, 2, 4, 5, 6, 7, 8, 9]), array([3]), array([], dtype=float64)],
 [array([0, 1, 2, 3, 5, 6, 7, 8, 9]), array([4]), array([], dtype=float64)],
 [array([0, 1, 2, 3, 4, 6, 7, 8, 9]), array([5]), array([], dtype=float64)],
 [array([0, 1, 2, 3, 4, 5, 7, 8, 9]), array([6]), array([], dtype=float64)],
 [array([0, 1, 2, 3, 4, 5, 6, 8, 9]), array([7]), array([], dtype=float64)],
 [array([0, 1, 2, 3, 4, 5, 6, 7, 9]), array([8]), array([], dtype=float64)],
 [array([0, 1, 2, 3, 4, 5, 6, 7, 8]), array([9]), array([], dtype=float64)],
 [array([2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1]), array([], dtype=float64)],
 [array([1, 3, 4, 5, 6, 7, 8, 9]), array([0, 2]), array

In [707]:
buff = []

def f(a, n, p):
    if n:
        for i in range(n+1, 0, -1):
            if i <= p:
                f(a+[i], n-i, i)
    else:
        buff.append([*a])
    return buff

def get_all_splits(n,groups):
    all_splits = []
    buff = f([], n, n)
    for item in buff:
        if len(item) < groups:
            delta = groups-len(item)
            all_splits.append(np.append(np.array(item),np.zeros(delta)).astype(int))
        if len(item) == groups:
            all_splits.append(np.array(item))
    return all_splits

NUE = np.arange(6)
all_splits = get_all_splits(n=len(NUE),groups=3)
all_splits

[array([6, 0, 0]),
 array([5, 1, 0]),
 array([4, 2, 0]),
 array([4, 1, 1]),
 array([3, 3, 0]),
 array([3, 2, 1]),
 array([2, 2, 2])]

In [703]:
list(permutations(np.arange(4)[::-1],2))

[(3, 2),
 (3, 1),
 (3, 0),
 (2, 3),
 (2, 1),
 (2, 0),
 (1, 3),
 (1, 2),
 (1, 0),
 (0, 3),
 (0, 2),
 (0, 1)]

In [712]:
def split_list(data, n):
    from itertools import combinations, chain
    for splits in combinations(range(1, len(data)), n-1):
        result = []
        prev = None
        for split in chain(splits, [None]):
            result.append(data[prev:split])
            prev = split
        yield result

list(split_list([1, 2, 3, 4, 5, 6], 3))

[[[1], [2], [3, 4, 5, 6]],
 [[1], [2, 3], [4, 5, 6]],
 [[1], [2, 3, 4], [5, 6]],
 [[1], [2, 3, 4, 5], [6]],
 [[1, 2], [3], [4, 5, 6]],
 [[1, 2], [3, 4], [5, 6]],
 [[1, 2], [3, 4, 5], [6]],
 [[1, 2, 3], [4], [5, 6]],
 [[1, 2, 3], [4, 5], [6]],
 [[1, 2, 3, 4], [5], [6]]]

In [735]:
def split_list(data, n):
    from itertools import combinations, chain
    for splits in combinations(range(1, len(data)), n-1):
        result = []
        prev = None
        for split in chain(splits, [None]):
            result.append(np.array(data[prev:split]))
            prev = split
        yield result

def get_splits(in_list,n_gr_max):
    groups = []
    for n_gr in range(1,n_gr_max+1):
        groups += list(split_list(in_list, n_gr))
    return groups

in_list = [1,2,3,4,5]
groups = get_splits(in_list,4)

for split in groups:
    G1=G2=G3=G4=None
    G1 = split[0]
    try: G2 = split[1]
    except: None
    try: G3 = split[2]
    except: None
    try: G4 = split[2]
    except: None
    print(G1,G2,G3,G4)

[[array([1, 2, 3, 4, 5])],
 [array([1]), array([2, 3, 4, 5])],
 [array([1, 2]), array([3, 4, 5])],
 [array([1, 2, 3]), array([4, 5])],
 [array([1, 2, 3, 4]), array([5])],
 [array([1]), array([2]), array([3, 4, 5])],
 [array([1]), array([2, 3]), array([4, 5])],
 [array([1]), array([2, 3, 4]), array([5])],
 [array([1, 2]), array([3]), array([4, 5])],
 [array([1, 2]), array([3, 4]), array([5])],
 [array([1, 2, 3]), array([4]), array([5])],
 [array([1]), array([2]), array([3]), array([4, 5])],
 [array([1]), array([2]), array([3, 4]), array([5])],
 [array([1]), array([2, 3]), array([4]), array([5])],
 [array([1, 2]), array([3]), array([4]), array([5])]]

[1 2 3 4 5] None None None
[1] [2 3 4 5] None None
[1 2] [3 4 5] None None
[1 2 3] [4 5] None None
[1 2 3 4] [5] None None
[1] [2] [3 4 5] [3 4 5]
[1] [2 3] [4 5] [4 5]
[1] [2 3 4] [5] [5]
[1 2] [3] [4 5] [4 5]
[1 2] [3 4] [5] [5]
[1 2 3] [4] [5] [5]
[1] [2] [3] [3]
[1] [2] [3 4] [3 4]
[1] [2 3] [4] [4]
[1 2] [3] [4] [4]


In [11]:
from sklearn.cluster import KMeans
import numpy as np
X = np.array([[1], [1], [3.1], [3], [1], [2]])
kmeans = KMeans(n_clusters=3, random_state=0).fit(X)
kmeans.labels_

array([0, 0, 1, 1, 0, 2], dtype=int32)